'use client';

import React from 'react';
import type { DartGeneratorSettings } from '@/lib/dart/types';

interface DartMethodsPanelProps {
  settings: DartGeneratorSettings;
  onSettingsChange: (settings: Partial<DartGeneratorSettings>) => void;
}

export function DartMethodsPanel({ settings, onSettingsChange }: DartMethodsPanelProps) {
  const isPlain = settings.codeStyle === 'plain';
  
  const methods = [
    {
      key: 'generateFromJson' as const,
      label: 'Generate fromJson',
      description: 'Factory constructor from Map',
      disabled: !isPlain,
    },
    {
      key: 'generateToJson' as const,
      label: 'Generate toJson',
      description: 'Convert to Map method',
      disabled: !isPlain,
    },
    {
      key: 'generateCopyWith' as const,
      label: 'Generate copyWith',
      description: 'Create modified copy',
      disabled: !isPlain,
    },
    {
      key: 'generateToString' as const,
      label: 'Generate toString',
      description: 'String representation',
      disabled: !isPlain,
    },
    {
      key: 'generateEquality' as const,
      label: 'Generate Equality',
      description: 'equals and hashCode',
      disabled: !isPlain,
    },
  ];

  return (
    <div className="settings-panel-content sp-stack-lg">
      <div className="settings-group">
        <span className="settings-group-title">Generated Methods</span>
        
        {!isPlain && (
          <div className="info-box">
            <p className="info-box-content">
              Methods are auto-generated by {settings.codeStyle === 'freezed' ? 'Freezed' : 'JSON Serializable'} via build_runner.
            </p>
          </div>
        )}

        {methods.map((method) => (
          <div key={method.key} className={`setting-toggle ${method.disabled ? 'disabled' : ''}`}>
            <div className="setting-toggle-info">
              <label className="setting-label">{method.label}</label>
              <p className="setting-hint">{method.description}</p>
            </div>
            <button
              onClick={() => !method.disabled && onSettingsChange({ [method.key]: !settings[method.key] })}
              disabled={method.disabled}
              className={`toggle-switch ${settings[method.key] && !method.disabled ? 'active' : ''} ${method.disabled ? 'disabled' : ''}`}
            >
              <span className="toggle-knob" />
            </button>
          </div>
        ))}
      </div>

      {/* Null Safety */}
      <div className="setting-toggle">
        <div className="setting-toggle-info">
          <label className="setting-label">Use Nullable Types</label>
          <p className="setting-hint">Type? for nullable fields</p>
        </div>
        <button
          onClick={() => onSettingsChange({ useNullableTypes: !settings.useNullableTypes })}
          className={`toggle-switch ${settings.useNullableTypes ? 'active' : ''}`}
        >
          <span className="toggle-knob" />
        </button>
      </div>
    </div>
  );
}
