/**
 * JSON to JavaScript Generator
 */

import type { JavaScriptGeneratorSettings, JavaScriptGenerationResult } from './types';
import { DEFAULT_JAVASCRIPT_SETTINGS } from './types';

/**
 * Convert string to camelCase
 */
function toCamelCase(str: string): string {
  return str
    .replace(/[-_\s]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ''))
    .replace(/^./, (c) => c.toLowerCase());
}

/**
 * Convert string to snake_case
 */
function toSnakeCase(str: string): string {
  return str
    .replace(/([A-Z])/g, '_$1')
    .replace(/[-\s]+/g, '_')
    .toLowerCase()
    .replace(/^_/, '');
}

/**
 * Convert string to PascalCase
 */
function toPascalCase(str: string): string {
  return str
    .replace(/[-_\s]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ''))
    .replace(/^./, (c) => c.toUpperCase());
}

/**
 * Convert property name based on naming convention
 */
function convertPropertyName(name: string, convention: string): string {
  switch (convention) {
    case 'camelCase':
      return toCamelCase(name);
    case 'PascalCase':
      return toPascalCase(name);
    case 'snake_case':
      return toSnakeCase(name);
    case 'preserve':
    default:
      return name;
  }
}

/**
 * Check if a key needs quoting
 */
function needsQuotes(key: string, alwaysQuote: boolean): boolean {
  if (alwaysQuote) return true;
  // Check if it's a valid JavaScript identifier
  const validIdentifier = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/;
  return !validIdentifier.test(key);
}

/**
 * Format a value for JavaScript output
 */
function formatValue(
  value: unknown,
  settings: JavaScriptGeneratorSettings,
  indentLevel: number
): string {
  const indent = settings.useSpaces ? ' '.repeat(settings.indentSize) : '\t';
  const currentIndent = indent.repeat(indentLevel);
  const nextIndent = indent.repeat(indentLevel + 1);
  const quote = settings.quoteStyle === 'single' ? "'" : '"';

  if (value === null) {
    return 'null';
  }

  if (value === undefined) {
    return 'undefined';
  }

  if (typeof value === 'string') {
    // Escape quotes and special characters
    const escaped = value
      .replace(/\\/g, '\\\\')
      .replace(settings.quoteStyle === 'single' ? /'/g : /"/g, settings.quoteStyle === 'single' ? "\\'" : '\\"')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r')
      .replace(/\t/g, '\\t');
    return `${quote}${escaped}${quote}`;
  }

  if (typeof value === 'number') {
    return String(value);
  }

  if (typeof value === 'boolean') {
    return String(value);
  }

  if (Array.isArray(value)) {
    if (value.length === 0) {
      return '[]';
    }

    const items = value.map((item) => {
      const formattedItem = formatValue(item, settings, indentLevel + 1);
      return `${nextIndent}${formattedItem}`;
    });

    const lastItemIndex = items.length - 1;
    const formattedItems = items.map((item, index) => {
      if (index === lastItemIndex && !settings.trailingComma) {
        return item;
      }
      return item + ',';
    });

    return `[\n${formattedItems.join('\n')}\n${currentIndent}]`;
  }

  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>);
    
    if (entries.length === 0) {
      return '{}';
    }

    const formattedEntries = entries.map(([key, val], index) => {
      const convertedKey = convertPropertyName(key, settings.propertyNaming);
      const quotedKey = needsQuotes(convertedKey, settings.quoteKeys)
        ? `${quote}${convertedKey}${quote}`
        : convertedKey;
      const formattedVal = formatValue(val, settings, indentLevel + 1);
      const trailingComma = index === entries.length - 1 && !settings.trailingComma ? '' : ',';
      return `${nextIndent}${quotedKey}: ${formattedVal}${trailingComma}`;
    });

    return `{\n${formattedEntries.join('\n')}\n${currentIndent}}`;
  }

  return 'undefined';
}

/**
 * Convert JSON to JavaScript
 */
export function convertJSONToJavaScript(
  jsonString: string,
  settings: JavaScriptGeneratorSettings = DEFAULT_JAVASCRIPT_SETTINGS
): JavaScriptGenerationResult {
  try {
    const json = JSON.parse(jsonString);
    const lines: string[] = [];
    const semi = settings.semicolon ? ';' : '';

    // Add comment if enabled
    if (settings.addComments) {
      lines.push('/**');
      lines.push(' * Generated JavaScript object');
      lines.push(' * Generated by JSON to JavaScript Converter');
      lines.push(' */');
    }

    // Format the value
    let formattedValue = formatValue(json, settings, 0);

    // Apply Object.freeze if enabled
    if (settings.freezeObject) {
      formattedValue = `Object.freeze(${formattedValue})`;
    }

    // Build the output based on export format
    switch (settings.exportFormat) {
      case 'none':
        if (settings.variableDeclaration === 'none') {
          lines.push(formattedValue + semi);
        } else {
          lines.push(`${settings.variableDeclaration} ${settings.variableName} = ${formattedValue}${semi}`);
        }
        break;

      case 'es6-default':
        if (settings.variableDeclaration === 'none') {
          lines.push(`export default ${formattedValue}${semi}`);
        } else {
          lines.push(`${settings.variableDeclaration} ${settings.variableName} = ${formattedValue}${semi}`);
          lines.push('');
          lines.push(`export default ${settings.variableName}${semi}`);
        }
        break;

      case 'es6-named':
        lines.push(`export ${settings.variableDeclaration || 'const'} ${settings.variableName} = ${formattedValue}${semi}`);
        break;

      case 'commonjs':
        if (settings.variableDeclaration === 'none') {
          lines.push(`module.exports = ${formattedValue}${semi}`);
        } else {
          lines.push(`${settings.variableDeclaration} ${settings.variableName} = ${formattedValue}${semi}`);
          lines.push('');
          lines.push(`module.exports = ${settings.variableName}${semi}`);
        }
        break;

      case 'umd':
        lines.push('(function (root, factory) {');
        lines.push("  if (typeof define === 'function' && define.amd) {");
        lines.push('    define([], factory);');
        lines.push("  } else if (typeof module === 'object' && module.exports) {");
        lines.push('    module.exports = factory();');
        lines.push('  } else {');
        lines.push(`    root.${settings.moduleName} = factory();`);
        lines.push('  }');
        lines.push("}(typeof self !== 'undefined' ? self : this, function () {");
        lines.push(`  return ${formattedValue.split('\n').map((line, i) => i === 0 ? line : '  ' + line).join('\n')}${semi}`);
        lines.push('}));');
        break;
    }

    return {
      success: true,
      code: lines.join('\n'),
    };
  } catch (error) {
    return {
      success: false,
      errors: [
        {
          message: error instanceof Error ? error.message : 'Unknown error during conversion',
          type: 'syntax',
        },
      ],
    };
  }
}
