import { test, expect } from './fixtures/test-base';

test.describe('JSON to Go Converter', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/json-to-go');
  });

  test('should load page with correct title', async ({ page }) => {
    await expect(page).toHaveTitle(/JSON to Go/i);
  });

  test('should display input and output panels', async ({ page }) => {
    // Check for input panel
    await expect(page.getByText('JSON Input')).toBeVisible();
    
    // Check for output panel
    await expect(page.getByText('Go Output')).toBeVisible();
  });

  test('should convert simple JSON to Go struct', async ({ page }) => {
    const testJson = JSON.stringify({
      name: 'John',
      age: 30,
      active: true
    }, null, 2);

    // Find and fill the input editor
    const inputEditor = page.locator('.monaco-editor').first();
    await inputEditor.click();
    
    // Use keyboard to clear and type
    await page.keyboard.press('Control+a');
    await page.keyboard.type(testJson);
    
    // Wait for conversion
    await page.waitForTimeout(500);
    
    // Check output contains Go struct syntax
    const outputContent = await page.locator('.monaco-editor').nth(1).textContent();
    expect(outputContent).toContain('type');
    expect(outputContent).toContain('struct');
  });

  test('should display settings sidebar', async ({ page }) => {
    // Check for settings tabs
    await expect(page.getByText('Naming')).toBeVisible();
    await expect(page.getByText('Tags')).toBeVisible();
    await expect(page.getByText('Options')).toBeVisible();
    await expect(page.getByText('Presets')).toBeVisible();
  });

  test('should allow changing root struct name', async ({ page }) => {
    // Click on Naming tab
    await page.getByText('Naming').click();
    
    // Find root struct name input
    const rootNameInput = page.getByPlaceholder('AutoGenerated');
    await rootNameInput.fill('User');
    
    // Verify the value changed
    await expect(rootNameInput).toHaveValue('User');
  });

  test('should have presets available', async ({ page }) => {
    // Click on Presets tab
    await page.getByText('Presets').click();
    
    // Check for preset options
    await expect(page.getByText('Default')).toBeVisible();
    await expect(page.getByText('API Response')).toBeVisible();
    await expect(page.getByText('MongoDB')).toBeVisible();
  });

  test('should display SEO content', async ({ page }) => {
    // Scroll to footer
    await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
    
    // Check for SEO sections
    await expect(page.getByText('How to Convert JSON to Go Structs')).toBeVisible();
    await expect(page.getByText('JSON to Go Converter Features')).toBeVisible();
  });

  test('should handle invalid JSON gracefully', async ({ page }) => {
    // Type invalid JSON
    const inputEditor = page.locator('.monaco-editor').first();
    await inputEditor.click();
    await page.keyboard.press('Control+a');
    await page.keyboard.type('{ invalid json }');
    
    // Wait for validation
    await page.waitForTimeout(500);
    
    // Output should be empty or show error indicator
    // The exact behavior depends on implementation
  });

  test('should be responsive on mobile viewport', async ({ page }) => {
    // Set mobile viewport
    await page.setViewportSize({ width: 375, height: 667 });
    
    // Page should still be functional
    await expect(page.getByText('JSON Input')).toBeVisible();
    await expect(page.getByText('Go Output')).toBeVisible();
  });

  test('should have copy button in output toolbar', async ({ page }) => {
    // Look for copy button
    const copyButton = page.getByRole('button', { name: /copy/i });
    await expect(copyButton).toBeVisible();
  });

  test('should have download button in output toolbar', async ({ page }) => {
    // Look for download button
    const downloadButton = page.getByRole('button', { name: /download/i });
    await expect(downloadButton).toBeVisible();
  });
});
