/**
 * Central tool configuration
 * Defines all tools available in the application
 */

export interface ToolMetadata {
  id: string;
  name: string;
  route: string;
  icon: string;
  description: string;
  category: 'converter' | 'formatter' | 'validator' | 'utility' | 'generator' | 'visualizer';
  keywords: string[];
  enabled: boolean;
}

export const TOOLS: ToolMetadata[] = [
  {
    id: 'json-to-openapi',
    name: 'JSON to OpenAPI',
    route: '/json-to-openapi',
    icon: 'fas fa-file-invoice',
    description: 'Convert JSON to OpenAPI 3.0 specifications',
    category: 'converter',
    keywords: ['openapi', 'swagger', 'api', 'rest', 'json', 'converter'],
    enabled: true,
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    route: '/csv-to-json',
    icon: 'fas fa-table',
    description: 'Convert CSV to JSON with custom formatting options',
    category: 'converter',
    keywords: ['csv', 'json', 'converter', 'table', 'data', 'parse'],
    enabled: true,
  },
  {
    id: 'json-to-yaml',
    name: 'JSON to YAML',
    route: '/json-to-yaml',
    icon: 'fas fa-arrow-right',
    description: 'Convert JSON to YAML with Kubernetes, Docker Compose, and Ansible presets',
    category: 'converter',
    keywords: ['json', 'yaml', 'yml', 'converter', 'config', 'kubernetes', 'docker'],
    enabled: true,
  },
  {
    id: 'json-diff',
    name: 'JSON Diff',
    route: '/json-diff',
    icon: 'fas fa-not-equal',
    description: 'Compare two JSON documents with visual diff, tree view, and detailed reports',
    category: 'utility',
    keywords: ['json', 'diff', 'compare', 'comparison', 'patch', 'delta', 'merge', 'changes'],
    enabled: true,
  },
  {
    id: 'json-editor',
    name: 'JSON Editor',
    route: '/json-editor',
    icon: 'fas fa-edit',
    description: 'Visual JSON editor with tree view, in-place editing, undo/redo, and search',
    category: 'utility',
    keywords: ['json', 'editor', 'tree', 'visual', 'edit', 'modify', 'structure'],
    enabled: true,
  },
  {
    id: 'json-to-xml',
    name: 'JSON to XML',
    route: '/json-to-xml',
    icon: 'fas fa-file-code',
    description: 'Convert JSON to XML with SOAP, RSS, Sitemap presets and customizable formatting',
    category: 'converter',
    keywords: ['json', 'xml', 'converter', 'soap', 'rss', 'sitemap', 'cdata', 'namespace'],
    enabled: true,
  },
  {
    id: 'json-encoder',
    name: 'JSON Encoder',
    route: '/json-encoder',
    icon: 'fas fa-lock',
    description: 'Encode JSON to URL, Base64, Hex, HTML Entity, and Unicode formats',
    category: 'utility',
    keywords: ['json', 'encoder', 'url', 'base64', 'hex', 'encode', 'escape', 'html', 'unicode'],
    enabled: true,
  },
  {
    id: 'json-decoder',
    name: 'JSON Decoder',
    route: '/json-decoder',
    icon: 'fas fa-unlock',
    description: 'Decode URL, Base64, Hex, HTML Entity, and Unicode encoded JSON with auto-detection',
    category: 'utility',
    keywords: ['json', 'decoder', 'url', 'base64', 'hex', 'decode', 'unescape', 'html', 'unicode', 'jwt'],
    enabled: true,
  },
  {
    id: 'json-escaper',
    name: 'JSON Escaper',
    route: '/json-escaper',
    icon: 'fas fa-shield-alt',
    description: 'Escape JSON strings for JavaScript, HTML, URL, and more with multiple modes',
    category: 'utility',
    keywords: ['json', 'escaper', 'escape', 'string', 'javascript', 'html', 'url', 'unicode', 'quotes'],
    enabled: true,
  },
  {
    id: 'json-unescaper',
    name: 'JSON Unescaper',
    route: '/json-unescaper',
    icon: 'fas fa-unlock-alt',
    description: 'Unescape JSON strings with auto-detection and multi-layer support',
    category: 'utility',
    keywords: ['json', 'unescaper', 'unescape', 'string', 'decode', 'escape', 'multi-layer', 'auto-detect'],
    enabled: true,
  },
  {
    id: 'json-flattener',
    name: 'JSON Flattener',
    route: '/json-flattener',
    icon: 'fas fa-compress-alt',
    description: 'Flatten nested JSON to key-value pairs with dot, bracket, or custom notation',
    category: 'utility',
    keywords: ['json', 'flattener', 'flatten', 'nested', 'dot', 'notation', 'key-value', 'bracket', 'underscore'],
    enabled: true,
  },
  {
    id: 'json-unflattener',
    name: 'JSON Unflattener',
    route: '/json-unflattener',
    icon: 'fas fa-expand-alt',
    description: 'Convert flattened JSON back to nested structure with auto-detection',
    category: 'utility',
    keywords: ['json', 'unflattener', 'unflatten', 'nested', 'expand', 'dot', 'notation', 'reconstruct', 'hierarchical'],
    enabled: true,
  },
  {
    id: 'json-generator',
    name: 'JSON Generator',
    route: '/json-generator',
    icon: 'fas fa-database',
    description: 'Generate realistic fake JSON test data with 50+ data types and custom schemas',
    category: 'generator',
    keywords: ['json', 'generator', 'fake', 'mock', 'test', 'data', 'faker', 'random', 'sample', 'bulk'],
    enabled: true,
  },
  {
    id: 'json-merge',
    name: 'JSON Merge',
    route: '/json-merge',
    icon: 'fas fa-code-branch',
    description: 'Merge multiple JSON objects with deep merge, array union, and conflict resolution',
    category: 'utility',
    keywords: ['json', 'merge', 'combine', 'deep', 'merge', 'concat', 'union', 'objects', 'arrays', 'conflict'],
    enabled: true,
  },
  {
    id: 'json-minifier',
    name: 'JSON Minifier',
    route: '/json-minifier',
    icon: 'fas fa-compress-arrows-alt',
    description: 'Minify and beautify JSON with compression stats, sort keys, and remove empty values',
    category: 'formatter',
    keywords: ['json', 'minifier', 'minify', 'compress', 'beautify', 'format', 'pretty', 'compact'],
    enabled: true,
  },
  {
    id: 'json-stats',
    name: 'JSON Stats',
    route: '/json-stats',
    icon: 'fas fa-chart-pie',
    description: 'Analyze JSON structure, types, keys, values, and data quality with visual insights',
    category: 'utility',
    keywords: ['json', 'stats', 'statistics', 'analyze', 'structure', 'types', 'quality', 'insights'],
    enabled: true,
  },
  {
    id: 'json-to-go',
    name: 'JSON to Go',
    route: '/json-to-go',
    icon: 'fas fa-code',
    description: 'Convert JSON to Go structs with JSON tags, nested support, and customizable options',
    category: 'converter',
    keywords: ['json', 'go', 'golang', 'struct', 'converter', 'code', 'generator', 'tags'],
    enabled: true,
  },
  {
    id: 'json-to-swift',
    name: 'JSON to Swift',
    route: '/json-to-swift',
    icon: 'fas fa-apple-alt',
    description: 'Convert JSON to Swift structs and classes with Codable, CodingKeys, and SwiftUI support',
    category: 'converter',
    keywords: ['json', 'swift', 'ios', 'codable', 'struct', 'class', 'converter', 'swiftui'],
    enabled: true,
  },
  {
    id: 'json-to-dart',
    name: 'JSON to Dart',
    route: '/json-to-dart',
    icon: 'fas fa-feather',
    description: 'Convert JSON to Dart classes with null safety, Freezed, JSON Serializable, and Flutter support',
    category: 'converter',
    keywords: ['json', 'dart', 'flutter', 'model', 'class', 'converter', 'freezed', 'fromjson'],
    enabled: true,
  },
  {
    id: 'json-to-java',
    name: 'JSON to Java',
    route: '/json-to-java',
    icon: 'fab fa-java',
    description: 'Convert JSON to Java POJO classes with Jackson, Gson, or Lombok annotations',
    category: 'converter',
    keywords: ['json', 'java', 'pojo', 'jackson', 'gson', 'lombok', 'converter', 'bean'],
    enabled: true,
  },
  {
    id: 'json-to-csharp',
    name: 'JSON to C#',
    route: '/json-to-csharp',
    icon: 'fas fa-code',
    description: 'Convert JSON to C# classes with Newtonsoft.Json or System.Text.Json attributes',
    category: 'converter',
    keywords: ['json', 'csharp', 'c#', 'dotnet', '.net', 'newtonsoft', 'converter', 'class'],
    enabled: true,
  },
  {
    id: 'json-to-python',
    name: 'JSON to Python',
    route: '/json-to-python',
    icon: 'fab fa-python',
    description: 'Convert JSON to Python dataclasses, Pydantic models, TypedDict, and more',
    category: 'converter',
    keywords: ['json', 'python', 'dataclass', 'pydantic', 'typeddict', 'converter', 'model'],
    enabled: true,
  },
  {
    id: 'json-to-crystal',
    name: 'JSON to Crystal',
    route: '/json-to-crystal',
    icon: 'fas fa-gem',
    description: 'Convert JSON to Crystal structs and classes with JSON::Serializable support',
    category: 'converter',
    keywords: ['json', 'crystal', 'struct', 'class', 'converter', 'serializable', 'model'],
    enabled: true,
  },
  {
    id: 'json-to-sql',
    name: 'JSON to SQL',
    route: '/json-to-sql',
    icon: 'fas fa-database',
    description: 'Convert JSON to SQL CREATE TABLE and INSERT statements for PostgreSQL, MySQL, SQLite, and more',
    category: 'converter',
    keywords: ['json', 'sql', 'postgresql', 'mysql', 'sqlite', 'table', 'insert', 'database'],
    enabled: true,
  },
  {
    id: 'json-to-objc',
    name: 'JSON to Objective-C',
    route: '/json-to-objc',
    icon: 'fas fa-mobile-alt',
    description: 'Convert JSON to Objective-C model classes with NSObject and dictionary methods',
    category: 'converter',
    keywords: ['json', 'objective-c', 'objc', 'ios', 'macos', 'nsobject', 'converter', 'model'],
    enabled: true,
  },
  {
    id: 'json-to-typescript',
    name: 'JSON to TypeScript',
    route: '/json-to-typescript',
    icon: 'fas fa-code',
    description: 'Convert JSON to TypeScript interfaces and type aliases with smart type inference',
    category: 'converter',
    keywords: ['json', 'typescript', 'ts', 'interface', 'type', 'converter', 'frontend'],
    enabled: true,
  },
  {
    id: 'json-to-javascript',
    name: 'JSON to JavaScript',
    route: '/json-to-javascript',
    icon: 'fab fa-js',
    description: 'Convert JSON to JavaScript object literals with ES6 modules, CommonJS, and UMD support',
    category: 'converter',
    keywords: ['json', 'javascript', 'js', 'object', 'es6', 'commonjs', 'module', 'converter'],
    enabled: true,
  },
  {
    id: 'json-to-kotlin',
    name: 'JSON to Kotlin',
    route: '/json-to-kotlin',
    icon: 'fas fa-code',
    description: 'Convert JSON to Kotlin data classes with Kotlinx, Gson, Moshi, or Jackson annotations',
    category: 'converter',
    keywords: ['json', 'kotlin', 'data class', 'android', 'kotlinx', 'gson', 'moshi', 'serialization'],
    enabled: true,
  },
  {
    id: 'json-to-cpp',
    name: 'JSON to C++',
    route: '/json-to-cpp',
    icon: 'fas fa-microchip',
    description: 'Convert JSON to C++ structs with nlohmann/json, RapidJSON, and Boost.JSON support',
    category: 'converter',
    keywords: ['json', 'cpp', 'c++', 'struct', 'nlohmann', 'rapidjson', 'boost', 'converter'],
    enabled: true,
  },
  {
    id: 'json-to-ruby',
    name: 'JSON to Ruby',
    route: '/json-to-ruby',
    icon: 'fas fa-gem',
    description: 'Convert JSON to Ruby hashes, Structs, OpenStruct, and classes with multiple syntax options',
    category: 'converter',
    keywords: ['json', 'ruby', 'hash', 'struct', 'openstruct', 'rails', 'converter', 'class'],
    enabled: true,
  },
  {
    id: 'json-to-elm',
    name: 'JSON to Elm',
    route: '/json-to-elm',
    icon: 'fas fa-leaf',
    description: 'Convert JSON to Elm type aliases with Json.Decode and Json.Encode functions',
    category: 'converter',
    keywords: ['json', 'elm', 'decoder', 'encoder', 'type', 'functional', 'converter', 'pipeline'],
    enabled: true,
  },
  {
    id: 'json-to-haskell',
    name: 'JSON to Haskell',
    route: '/json-to-haskell',
    icon: 'fas fa-lambda',
    description: 'Convert JSON to Haskell records with Aeson FromJSON/ToJSON instances',
    category: 'converter',
    keywords: ['json', 'haskell', 'aeson', 'record', 'fromjson', 'tojson', 'generic', 'deriving'],
    enabled: true,
  },
  {
    id: 'json-validator',
    name: 'JSON Validator',
    route: '/json-validator',
    icon: 'fas fa-check-circle',
    description: 'Validate JSON syntax with detailed errors, auto-fix, and RFC 8259 compliance',
    category: 'validator',
    keywords: ['json', 'validator', 'validate', 'syntax', 'checker', 'lint', 'rfc8259', 'auto-fix', 'errors'],
    enabled: true,
  },
  {
    id: 'json-fixer',
    name: 'JSON Fixer',
    route: '/json-fixer',
    icon: 'fas fa-bug',
    description: 'Interactive JSON debugging with detailed error explanations and one-by-one fixing',
    category: 'utility',
    keywords: ['json', 'fixer', 'debugger', 'error', 'interactive', 'fix', 'learn', 'syntax'],
    enabled: true,
  },
  {
    id: 'json-repair',
    name: 'JSON Repair',
    route: '/json-repair',
    icon: 'fas fa-wrench',
    description: 'Automatically repair broken JSON syntax with one-click fixing and presets',
    category: 'utility',
    keywords: ['json', 'repair', 'fix', 'broken', 'auto', 'quotes', 'commas', 'brackets'],
    enabled: true,
  },
  {
    id: 'json-cleaner',
    name: 'JSON Cleaner',
    route: '/json-cleaner',
    icon: 'fas fa-broom',
    description: 'Clean, transform, and sanitize JSON data with key conversion and type transformation',
    category: 'utility',
    keywords: ['json', 'cleaner', 'clean', 'transform', 'sanitize', 'remove', 'null', 'empty', 'keys'],
    enabled: true,
  },
  {
    id: 'json-schema-validator',
    name: 'JSON Schema Validator',
    route: '/json-schema-validator',
    icon: 'fas fa-file-alt',
    description: 'Validate JSON data against JSON Schema definitions with draft support',
    category: 'validator',
    keywords: ['json', 'schema', 'validator', 'validate', 'draft-07', '2020-12', 'openapi', 'specification'],
    enabled: true,
  },
  {
    id: 'json-to-schema',
    name: 'JSON to Schema',
    route: '/json-to-schema',
    icon: 'fas fa-project-diagram',
    description: 'Generate schemas from JSON in 10+ formats: JSON Schema, TypeScript, Zod, GraphQL, and more',
    category: 'generator',
    keywords: ['json', 'schema', 'generator', 'typescript', 'zod', 'yup', 'graphql', 'mongoose', 'rust', 'go'],
    enabled: true,
  },
  {
    id: 'json-to-protobuf',
    name: 'JSON to Protobuf',
    route: '/json-to-protobuf',
    icon: 'fas fa-cube',
    description: 'Convert JSON to Protocol Buffer schemas with proto2/proto3 support',
    category: 'converter',
    keywords: ['json', 'protobuf', 'protocol buffers', 'proto', 'grpc', 'schema', 'serialization'],
    enabled: true,
  },
  {
    id: 'json-to-avro',
    name: 'JSON to Avro',
    route: '/json-to-avro',
    icon: 'fas fa-database',
    description: 'Convert JSON to Apache Avro schemas with logical type inference',
    category: 'converter',
    keywords: ['json', 'avro', 'apache avro', 'schema', 'kafka', 'streaming', 'big data'],
    enabled: true,
  },
  {
    id: 'json-to-parquet',
    name: 'JSON to Parquet',
    route: '/json-to-parquet',
    icon: 'fas fa-columns',
    description: 'Convert JSON to Apache Parquet schemas with compression options',
    category: 'converter',
    keywords: ['json', 'parquet', 'apache parquet', 'columnar', 'analytics', 'big data', 'spark'],
    enabled: true,
  },
  {
    id: 'json-to-flow',
    name: 'JSON Visualizer',
    route: '/json-to-flow',
    icon: 'fas fa-project-diagram',
    description: 'Visualize JSON data as interactive flowchart diagrams',
    category: 'visualizer',
    keywords: ['json', 'visualizer', 'flowchart', 'diagram', 'tree', 'graph', 'visualization'],
    enabled: true,
  },
  {
    id: 'jsonpath-tester',
    name: 'JSONPath Tester',
    route: '/jsonpath-tester',
    icon: 'fas fa-search',
    description: 'Test JSONPath expressions against JSON data in real-time',
    category: 'utility',
    keywords: ['jsonpath', 'query', 'tester', 'expression', 'filter', 'selector', 'json', 'xpath'],
    enabled: true,
  },
  {
    id: 'jmespath-tester',
    name: 'JMESPath Tester',
    route: '/jmespath-tester',
    icon: 'fas fa-filter',
    description: 'Test JMESPath queries against JSON data with AWS CLI compatible syntax',
    category: 'utility',
    keywords: ['jmespath', 'query', 'tester', 'filter', 'aws', 'cli', 'json', 'transform'],
    enabled: true,
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    route: '/json-formatter',
    icon: 'fas fa-indent',
    description: 'Format and beautify JSON with tree view, validation, and data cleaning options',
    category: 'formatter',
    keywords: ['json', 'formatter', 'beautifier', 'pretty print', 'format', 'tree view', 'validate', 'indent'],
    enabled: true,
  },
  {
    id: 'json-to-excel',
    name: 'JSON to Excel',
    route: '/json-to-excel',
    icon: 'fas fa-file-excel',
    description: 'Convert JSON to Excel (XLSX, XLS, CSV) with nested flattening and column customization',
    category: 'converter',
    keywords: ['json', 'excel', 'xlsx', 'xls', 'csv', 'spreadsheet', 'converter', 'export', 'table'],
    enabled: true,
  },
];

/**
 * Get tool configuration by ID
 */
export function getToolById(id: string): ToolMetadata | undefined {
  return TOOLS.find(tool => tool.id === id);
}

/**
 * Get tool configuration by route
 */
export function getToolByRoute(route: string): ToolMetadata | undefined {
  return TOOLS.find(tool => tool.route === route);
}

/**
 * Get all enabled tools
 */
export function getEnabledTools(): ToolMetadata[] {
  return TOOLS.filter(tool => tool.enabled);
}

/**
 * Get tools by category
 */
export function getToolsByCategory(category: ToolMetadata['category']): ToolMetadata[] {
  return TOOLS.filter(tool => tool.category === category && tool.enabled);
}
