/**
 * Types for JSON to Go converter
 */

import type { BaseGeneratorSettings, ValidationError } from '../code-gen/types';

/**
 * Go-specific generator settings
 */
export interface GoGeneratorSettings extends BaseGeneratorSettings {
  // Naming
  rootClassName: string;
  
  // Tags
  includeJsonTags: boolean;
  includeOmitempty: boolean;
  includeYamlTags: boolean;
  includeXmlTags: boolean;
  includeBsonTags: boolean;
  
  // Type options
  usePointerForNullable: boolean;
  preferInt64: boolean;
  useFloat32: boolean;
  
  // Structure
  inlineNestedStructs: boolean;
  sortFields: boolean;
  
  // Formatting
  indentation: number | 'tab';
  addComments: boolean;
}

/**
 * Default settings
 */
export const DEFAULT_GO_SETTINGS: GoGeneratorSettings = {
  rootClassName: 'AutoGenerated',
  indentation: 'tab',
  useNullableTypes: true,
  
  // Tags
  includeJsonTags: true,
  includeOmitempty: false,
  includeYamlTags: false,
  includeXmlTags: false,
  includeBsonTags: false,
  
  // Type options
  usePointerForNullable: false,
  preferInt64: false,
  useFloat32: false,
  
  // Structure
  inlineNestedStructs: false,
  sortFields: false,
  
  // Formatting
  addComments: false,
};

/**
 * Go conversion result
 */
export interface GoConversionResult {
  success: boolean;
  code?: string;
  errors?: ValidationError[];
  structCount?: number;
}

/**
 * Go struct preset
 */
export interface GoPreset {
  id: string;
  name: string;
  description: string;
  settings: Partial<GoGeneratorSettings>;
}
