'use client';

import React from 'react';
import type { GoGeneratorSettings } from '@/lib/go/types';

interface GoNamingPanelProps {
  settings: GoGeneratorSettings;
  onSettingsChange: (settings: Partial<GoGeneratorSettings>) => void;
}

export function GoNamingPanel({ settings, onSettingsChange }: GoNamingPanelProps) {
  return (
    <div className="settings-panel-content">
      {/* Root Struct Name */}
      <div className="setting-group">
        <label>Root Struct Name</label>
        <input
          type="text"
          value={settings.rootClassName}
          onChange={(e) => onSettingsChange({ rootClassName: e.target.value || 'AutoGenerated' })}
          placeholder="AutoGenerated"
        />
        <span className="setting-hint">Name for the root struct (use PascalCase)</span>
      </div>

      {/* Sort Fields */}
      <div className="setting-toggle">
        <div className="setting-toggle-info">
          <label>Sort Fields Alphabetically</label>
          <span className="setting-hint">Order struct fields A-Z</span>
        </div>
        <button
          type="button"
          role="switch"
          aria-checked={settings.sortFields}
          onClick={() => onSettingsChange({ sortFields: !settings.sortFields })}
          className={`toggle-switch ${settings.sortFields ? 'active' : ''}`}
        >
          <span className="toggle-knob" />
        </button>
      </div>

      {/* Add Comments */}
      <div className="setting-toggle">
        <div className="setting-toggle-info">
          <label>Add Comments</label>
          <span className="setting-hint">Include struct documentation comments</span>
        </div>
        <button
          type="button"
          role="switch"
          aria-checked={settings.addComments}
          onClick={() => onSettingsChange({ addComments: !settings.addComments })}
          className={`toggle-switch ${settings.addComments ? 'active' : ''}`}
        >
          <span className="toggle-knob" />
        </button>
      </div>
    </div>
  );
}
